config/routes.rb
Rails.application.routes.draw do

  # PANEL
  get '/extensiones', to: 'panel#extensiones'
  get '/', to: 'panel#extensiones'

  post '/extensiones', to: 'panel#createExtensions'
  delete '/extensiones', to: 'panel#deleteExtensions'

  put '/empleados', to: 'panel#editEmployees'

  get '/departamentos', to: 'panel#departamentos'
  post '/departamentos', to: 'panel#createDepartments'
  put '/departamentosTime', to: 'panel#editTimeDepartament'
  put '/departamentosMode', to: 'panel#editModeDepartament'
  put '/departamentosExtensiones', to: 'panel#addExtensionsToDpto'
  delete '/departamentos', to: 'panel#deleteDepartamentos'

  # TEST
  get '/test', to: 'panel#test'

  # API
  namespace :api do
      resources :pbxapi, only: [:index, :create, :destroy, :update, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/extension.rb
class Extension < ApplicationRecord
    self.table_name = "extensions"
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
    include ExtensionsHelper
  before_action :set_extension, only: [:show, :edit, :update, :destroy]

  # GET /extensions
  # GET /extensions.json
  def index
    @extensions = Extension.all

    # Init pbx
    o = ExtensionesHelper.new
    o.inicializarCentralita

    # esto lo recibe desde un formulario
    o.crearExtension('101')



  end

  # GET /extensions/1
  # GET /extensions/1.json
  def show
  end

  # GET /extensions/new
  def new
    @extension = Extension.new
  end

  # GET /extensions/1/edit
  def edit
  end

  # POST /extensions
  # POST /extensions.json
  def create
    @extension = Extension.new(extension_params)

    respond_to do |format|
      if @extension.save
        format.html { redirect_to @extension, notice: 'Extension was successfully created.' }
        format.json { render :show, status: :created, location: @extension }
      else
        format.html { render :new }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extensions/1
  # PATCH/PUT /extensions/1.json
  def update
    respond_to do |format|
      if @extension.update(extension_params)
        format.html { redirect_to @extension, notice: 'Extension was successfully updated.' }
        format.json { render :show, status: :ok, location: @extension }
      else
        format.html { render :edit }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extensions/1
  # DELETE /extensions/1.json
  def destroy
    @extension.destroy
    respond_to do |format|
      format.html { redirect_to extensions_url, notice: 'Extension was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extension
      @extension = Extension.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extension_params
      params.require(:extension).permit(:context, :exten, :priority, :app, :appdata)
    end
end

app/views/extensions/_form.html.erb
<%= form_with(model: extension, local: true) do |form| %>
  <% if extension.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

      <ul>
      <% extension.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_field :context, id: :extension_context %>
  </div>

  <div class="field">
    <%= form.label :exten %>
    <%= form.text_field :exten, id: :extension_exten %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority, id: :extension_priority %>
  </div>

  <div class="field">
    <%= form.label :app %>
    <%= form.text_field :app, id: :extension_app %>
  </div>

  <div class="field">
    <%= form.label :appdata %>
    <%= form.text_field :appdata, id: :extension_appdata %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/extensions/edit.html.erb
<h1>Editing Extension</h1>

<%= render 'form', extension: @extension %>

<%= link_to 'Show', @extension %> |
<%= link_to 'Back', extensions_path %>

app/views/extensions/index.html.erb
<p id="notice"><%= notice %></p>


<%= @test %>

<h1>Extensions</h1>


<table>
  <thead>
    <tr>
      <th>Context</th>
      <th>Exten</th>
      <th>Priority</th>
      <th>App</th>
      <th>Appdata</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extensions.each do |extension| %>
      <tr>
        <td><%= extension.context %></td>
        <td><%= extension.exten %></td>
        <td><%= extension.priority %></td>
        <td><%= extension.app %></td>
        <td><%= extension.appdata %></td>
        <td><%= link_to 'Show', extension %></td>
        <td><%= link_to 'Edit', edit_extension_path(extension) %></td>
        <td><%= link_to 'Destroy', extension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Extension', new_extension_path %>

app/views/extensions/new.html.erb
<h1>New Extension</h1>

<%= render 'form', extension: @extension %>

<%= link_to 'Back', extensions_path %>

app/views/extensions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Context:</strong>
  <%= @extension.context %>
</p>

<p>
  <strong>Exten:</strong>
  <%= @extension.exten %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @extension.priority %>
</p>

<p>
  <strong>App:</strong>
  <%= @extension.app %>
</p>

<p>
  <strong>Appdata:</strong>
  <%= @extension.appdata %>
</p>

<%= link_to 'Edit', edit_extension_path(@extension) %> |
<%= link_to 'Back', extensions_path %>